services:
  server:
    container_name: copycord-server
    image: ghcr.io/copycord/server:latest
    environment:
      - SERVER_TOKEN=123456789123456789 # Discord bot token, must be invited into the cloned server
      - CLONE_GUILD_ID=123456789 # ID of the server you created to be cloned
      - DELETE_CHANNELS=False # Should we delete channels after they are deleted from the host server? WARNING: This will delete the channel and all of its messages
      - DELETE_THREADS=False # Should we delete threads after they are deleted from the host server? WARNING: This will delete the thread and all of its messages
    volumes:
      - ./data:/data
    restart: unless-stopped

  client:
    container_name: copycord-client
    image: ghcr.io/copycord/client:latest
    environment:
      - CLIENT_TOKEN=123456789123456789 # Discord user account token, see "Getting Started"
      - HOST_GUILD_ID=123456789 # ID of the server we wil be cloning
    volumes:
      - ./data:/data
    depends_on:
      - server
    restart: unless-stopped