services:
<<<<<<< HEAD
  server:
    image: ghcr.io/copycord/copycord-server:v1.8.0
    container_name: copycord-server
    env_file:
      - .env
    volumes:
      - ./data:/data

  client:
    image: ghcr.io/copycord/copycord-client:v1.8.0
    container_name: copycord-client
    env_file:
      - .env
    volumes:
      - ./data:/data
    depends_on:
      - server
=======
  admin:
    image: ghcr.io/copycord/copycord:v2.0.0
    environment:
      - ROLE=admin
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data

  server:
    image: ghcr.io/copycord/copycord:v2.0.0
    environment:
      - ROLE=server
    volumes:
      - ./data:/data
    depends_on:
      - admin

  client:
    image: ghcr.io/copycord/copycord:v2.0.0
    environment:
      - ROLE=client
    volumes:
      - ./data:/data
    depends_on:
      - admin
>>>>>>> web-ui
