services:
  admin:
    image: copycord-local:dev
    container_name: copycord-admin
    environment:
      - ROLE=admin
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    restart: unless-stopped

  server:
    image: copycord-local:dev
    container_name: copycord-server
    environment:
      - ROLE=server
    volumes:
      - ./data:/data
    depends_on:
      - admin
    restart: unless-stopped

  client:
    image: copycord-local:dev
    container_name: copycord-client
    environment:
      - ROLE=client
    volumes:
      - ./data:/data
    depends_on:
      - admin
    restart: unless-stopped