name: Build & publish Copycord test containers

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image tag to publish (e.g., testing-1, v1.2.3-beta.1)"
        required: true
        default: "testing"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive lower-case owner
        id: vars
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Build & push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./code/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.owner }}/copycord:${{ github.event.inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
