name: Build & publish Copycord container

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            platform: linux/amd64
          - arch: arm64
            platform: linux/arm64

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive lower-case owner
        id: vars
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Build & push per-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./code/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.owner }}/copycord:${{ github.ref_name }}-${{ matrix.arch }}
            ghcr.io/${{ steps.vars.outputs.owner }}/copycord:latest-${{ matrix.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
